env:
 global:
   - R_BUILD_ARGS="--no-manual"
   - R_CHECK_ARGS="--as-cran --no-manual"
   - BOOTSTRAP_LATEX=""

init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

build_script:
  - sudo apt-get update -qq
  - sudo apt-get install libxslt1-dev
  - travis-tool.sh bootstrap
  - travis-tool.sh install_r_binary geiger phytools knitr testthat rfigshare ape plyr taxize reshape2 httr rjava
  - travis-tool.sh install_github cboettig/Sxslt
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - travis-tool.sh dump_logs

notifications:
  - provider: Slack
    auth_token:
      secure: S3AcHEoJHUtahR5N8ConStS8oV/+x34tS1bDGM3OD0QxDKBBxufeiMmXQsId1gZu
    channel: package-development
